{% set name = "hxntools" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8180c45143bab859821029ac9e47e78bb8ecde0456663dd774504e648e451fc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bluesky
    - boltons
    - cycler
    - databroker
    - h5py
    - matplotlib-base
    - nslsii
    - numpy
    - ophyd
    - pandas
    - pyepics
    - scipy

test:
  requires:   # [not win]
    - pip        # [not win]
  commands:   # [not win]
    - pip check  # [not win]
  imports:
    - hxntools

about:
  home: https://github.com/NSLS-II-HXN/hxntools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: NSLS-II Hard X-ray Nanoprobe data acquisition tools

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
