{% set name = "hxntools" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca98fa157decb05759f2c5e5f290d43fc1c1e7b8a080d104c72ecf4375d7eafb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bluesky
    - boltons
    - cycler
    - databroker
    - h5py
    - matplotlib-base
    - nslsii
    - numpy
    - ophyd
    - pandas
    - pyepics
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - hxntools

about:
  home: https://github.com/NSLS-II-HXN/hxntools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: NSLS-II Hard X-ray Nanoprobe data acquisition tools

extra:
  recipe-maintainers:
    - mrakitin
    - dmgav
    - conda-forge/event-model
