{% set name = "hxntools" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bd4e3f83b68f68a6eb3405d7f045d7ac82c6959fdb937559cfd7ae31a2b3c11

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bluesky
    - boltons
    - cycler
    - databroker
    - h5py
    - matplotlib-base
    - nslsii
    - numpy
    - ophyd
    - pandas
    - pyepics
    - scipy

test:
  imports:
    - hxntools

about:
  home: https://github.com/NSLS-II-HXN/hxntools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: NSLS-II Hard X-ray Nanoprobe data acquisition tools

extra:
  recipe-maintainers:
    - mrakitin
    - dmgav
    - kbeeperez
    - conda-forge/event-model
