{% set name = "hxntools" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8e2f3b41a1e1943ef76296b5d0420e0bc8f3e91771181546b7c583872ebe779

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bluesky
    - boltons
    - cycler
    - databroker
    - h5py
    - matplotlib-base
    - nslsii
    - numpy
    - ophyd
    - pandas
    - pyepics
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - hxntools

about:
  home: https://github.com/NSLS-II-HXN/hxntools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: NSLS-II Hard X-ray Nanoprobe data acquisition tools

extra:
  recipe-maintainers:
    - mrakitin
    - dmgav
    - conda-forge/event-model
